import { Ingredient } from 'domain/entities/ingredient';
import { SpiritType } from 'domain/enums/spirit-type';

export function getStaticIngredients() {
    return [...currentIngredients];
}

const currentIngredients: Ingredient[] = [
    { id: '1', name: 'Light Rum', spiritType: SpiritType.Rum },
    { id: '2', name: 'Lime Juice', spiritType: SpiritType.None },
    { id: '3', name: 'Simple syrup', spiritType: SpiritType.None },
    { id: '4', name: 'Soda Water', spiritType: SpiritType.None },
    { id: '5', name: 'Mint', spiritType: SpiritType.None },
    { id: '6', name: 'Gin', spiritType: SpiritType.Gin },
    { id: '7', name: 'Tonic Water', spiritType: SpiritType.None },
    { id: '8', name: 'Vodka', spiritType: SpiritType.Vodka },
    { id: '9', name: 'Tomato Juice', spiritType: SpiritType.None },
    { id: '10', name: 'Lemon Juice', spiritType: SpiritType.None },
    { id: '11', name: 'Tabasco sauce', spiritType: SpiritType.None },
    { id: '12', name: 'Worcestershire sauce', spiritType: SpiritType.None },
    { id: '13', name: 'Black Pepper', spiritType: SpiritType.None },
    { id: '14', name: 'Celery Salt', spiritType: SpiritType.None },
    { id: '15', name: 'Celery', spiritType: SpiritType.None },
    { id: '16', name: 'Powdered Sugar', spiritType: SpiritType.None },
    { id: '17', name: 'Cranberry Juice', spiritType: SpiritType.None },
    { id: '18', name: 'Tequila', spiritType: SpiritType.Tequila },
    { id: '19', name: 'Orange liqueur', spiritType: SpiritType.None },
    { id: '20', name: 'Strawberry', spiritType: SpiritType.None },
    { id: '21', name: 'Spiced rum', spiritType: SpiritType.Rum },
    { id: '22', name: 'Amaretto', spiritType: SpiritType.None },
    { id: '23', name: 'Egg white', spiritType: SpiritType.None },
    { id: '24', name: 'Ginger Beer', spiritType: SpiritType.None },
    { id: '25', name: 'Coconut Cream', spiritType: SpiritType.None },
    { id: '26', name: 'Pineapple Juice', spiritType: SpiritType.None },
    { id: '27', name: 'Angostura bitters', spiritType: SpiritType.None },
    { id: '28', name: 'Bourbon Whiskey', spiritType: SpiritType.WiskeyScotch },
    { id: '29', name: 'Apricot Brandy', spiritType: SpiritType.CognacBrandy },
    { id: '30', name: 'Grenadine', spiritType: SpiritType.None },
    { id: '31', name: 'Dry Vermouth', spiritType: SpiritType.None },
    { id: '32', name: 'Olive', spiritType: SpiritType.None },
    { id: '33', name: 'Galliano', spiritType: SpiritType.None },
    { id: '34', name: 'Coffee', spiritType: SpiritType.None },
    { id: '35', name: 'Cream', spiritType: SpiritType.None },
    { id: '36', name: 'Campari', spiritType: SpiritType.None },
    { id: '37', name: 'Sweet Vermouth', spiritType: SpiritType.None },
    { id: '38', name: 'Triple Sec', spiritType: SpiritType.None },
    { id: '39', name: 'Southern Comfort', spiritType: SpiritType.WiskeyScotch },
    { id: '40', name: 'Sloe Gin', spiritType: SpiritType.Gin },
    { id: '41', name: 'Irish Whiskey', spiritType: SpiritType.WiskeyScotch },
    { id: '42', name: 'Sugar', spiritType: SpiritType.None },
    { id: '43', name: 'Coffee Liqueur', spiritType: SpiritType.None },
    { id: '44', name: 'Blue Curacao', spiritType: SpiritType.None },
    { id: '45', name: 'Sprite', spiritType: SpiritType.None },
    { id: '46', name: 'Salt', spiritType: SpiritType.None },
    { id: '47', name: 'Creme De Cacao', spiritType: SpiritType.None },
    { id: '48', name: 'Light Cream', spiritType: SpiritType.None },
    { id: '49', name: 'Nutmeg', spiritType: SpiritType.None },
    { id: '50', name: 'Brandy', spiritType: SpiritType.CognacBrandy },
    { id: '51', name: 'Lemon Vodka', spiritType: SpiritType.Vodka },
    { id: '52', name: 'Blended Whiskey', spiritType: SpiritType.WiskeyScotch },
    { id: '53', name: 'Blackberry brandy', spiritType: SpiritType.CognacBrandy },
    { id: '54', name: 'Dark rum', spiritType: SpiritType.Rum },
    { id: '55', name: 'Kahlua', spiritType: SpiritType.None },
    { id: '56', name: 'Scotch', spiritType: SpiritType.WiskeyScotch },
    { id: '57', name: 'Maraschino liqueur', spiritType: SpiritType.None },
    { id: '58', name: 'Orange bitters', spiritType: SpiritType.None },
    { id: '59', name: 'Egg yolk', spiritType: SpiritType.None },
    { id: '60', name: 'Champagne', spiritType: SpiritType.None },
    { id: '61', name: 'Cognac', spiritType: SpiritType.CognacBrandy },
    { id: '62', name: 'Chocolate Ice-cream', spiritType: SpiritType.None },
    { id: '63', name: 'Coca-Cola', spiritType: SpiritType.None },
    { id: '64', name: 'Orange Juice', spiritType: SpiritType.None },
    { id: '65', name: 'Apple brandy', spiritType: SpiritType.CognacBrandy },
    { id: '66', name: 'Orgeat Syrup', spiritType: SpiritType.None },
    { id: '67', name: 'Sweet and Sour', spiritType: SpiritType.None },
    { id: '68', name: 'Creme De Cassis', spiritType: SpiritType.None },
    { id: '69', name: 'Peach Schnapps', spiritType: SpiritType.None },
    { id: '70', name: 'Grapefruit Juice', spiritType: SpiritType.None },
    { id: '71', name: 'Coconut liqueur', spiritType: SpiritType.None },
    { id: '72', name: 'Malibu rum', spiritType: SpiritType.Rum },
    { id: '73', name: 'Lager Beer', spiritType: SpiritType.None },
    { id: '74', name: 'Absinthe', spiritType: SpiritType.None },
    { id: '75', name: 'Licor 43', spiritType: SpiritType.None },
    { id: '76', name: 'Blueberry Juice', spiritType: SpiritType.None },
    { id: '77', name: 'Milk', spiritType: SpiritType.None },
    { id: '78', name: 'Melon Liqueur', spiritType: SpiritType.None },
    { id: '79', name: 'Ouzo', spiritType: SpiritType.None },
    { id: '80', name: 'Aperol', spiritType: SpiritType.None },
    { id: '81', name: 'Peach Brandy', spiritType: SpiritType.CognacBrandy },
    { id: '82', name: 'Kiwi', spiritType: SpiritType.None },
    { id: '83', name: 'Elderflower cordial', spiritType: SpiritType.None },
    { id: '84', name: 'Blackberries', spiritType: SpiritType.None },
    { id: '85', name: 'Orange Curacao', spiritType: SpiritType.None },
    { id: '86', name: 'Prosecco', spiritType: SpiritType.None },
    { id: '87', name: 'White wine', spiritType: SpiritType.None },
    { id: '88', name: 'Blueberries', spiritType: SpiritType.None },
    { id: '89', name: 'Agave Syrup', spiritType: SpiritType.None },
    { id: '90', name: 'Mezcal', spiritType: SpiritType.Tequila },
    { id: '91', name: 'Water', spiritType: SpiritType.None },
    { id: '92', name: 'Cointreau', spiritType: SpiritType.None },
    { id: '93', name: 'Pisco', spiritType: SpiritType.None },
    { id: '94', name: 'Aquafaba', spiritType: SpiritType.None },
];
