name: Release PlayStore

on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install app dependencies
              run: npm ci

            - name: Create .env file
              uses: SpicyPizza/create-envfile@v2.0.2
              with:
                  envkey_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

            - name: Build Web
              run: npm run build:play-store

            - name: Run Web tests
              run: npm t

            - name: Capacitor update
              run: npx cap update

            - name: Build app bundle
              run: cd android && gradle bundle

            - name: Extract Android signing key from env
              run: |
                  echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
                  base64 -d android/release.jks.base64 > android/release.decrypted.jks

            - name: Sign dev build
              run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab key0

            - name: Upload release bundle
              uses: actions/upload-artifact@v3
              with:
                  name: app-release
                  path: android/app/build/outputs/bundle/release/app-release-signed.aab
                  retention-days: 60
